version: '3.3'
services:
    # Define service mysql
    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_DATABASE: 'icetea'
        MYSQL_USER: 'icetea'
        MYSQL_PASSWORD: 'abc@12345678'
        MYSQL_ROOT_PASSWORD: 'abc@12345678'
      ports:
        - "4406:3306"
      expose:
        - "4406"
      volumes:
        - docuguard_db:/var/lib/mysql
      networks:
        - docuguard

    # Define service IPFS Node
    ipfs:
      image: ipfs/go-ipfs:latest
      ports:
        - "4001:4001"
        - "8080:8080"
        - "127.0.0.1:5001:5001"
      expose:
        - "4001"
        - "8080"
        - "5001"
      volumes:
        # Path examples on Windows
        # - C:\Users\ASUS\ipfs_staging:/export
        # - C:\Users\ASUS\ipfs_data:/data/ipfs
        # Path on Linux
        - /var/ipfs_storage/export:/export
        - /var/ipfs_storage/ipfs:/ipfs
      networks:
        - docuguard
    # Define service docuguard
    service:
      image: docuguard-service
      depends_on:
        - "ipfs"
        - "db"
      build: .
      # Run only Ubuntu test environment. 
      # On windows should comment this extra_hosts
      # extra_hosts:
      #   - "host.docker.internal:172.17.0.1"
      environment:
        DB_HOST: 'db'
        DB_PORT: 3306
        DB_USER: 'icetea'
        DB_PASSWORD: 'abc@12345678'
        DB_NAME: 'icetea'
        IPFS_HOST: 'http://ipfs:5001'
        WAIT_HOSTS: db:3306, ipfs:5001
      ports:
        - "5050:5050"
      expose:
        - "5050"
      networks:
        - docuguard
# Names our volume
volumes:
  docuguard_db:

networks:
  docuguard:
    name: docuguard_network
    driver: bridge